name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-02"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL= 'prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMGMyODAzMGQtZjIzNC00MjRmLWFhZTEtOTZlNzdmZDVlNzE2IiwidGVuYW50X2lkIjoiNDhlYjg1YmZhNjQ3YzYwNzFjZDI4YzhhNTU0NWQwNzIzYTllMWU3ODIwZmRjNmZiM2EzOWExNzRhNmYyYmVmNiIsImludGVybmFsX3NlY3JldCI6IjYyM2VlZGM4LWVlOTktNGJkMi1hZjg0LTRjMDQ3MDUyM2I1OCJ9.od1owmHRe3lwvT1ya-FigE8BOWye-sORjNvlgcHPJk4'
JWT_SECRET="secretKey"